import { PageHeader } from '../../shared/ui/PageHeader';
import { Button } from '../../shared/ui/Button';
import { Card } from '../../shared/ui/Card';
import { useMasterProStore } from '../../app/store/useMasterProStore';
import { formatMoney } from '../../shared/utils/money';
function downloadBlob(content:string, filename:string, type:string){ const blob=new Blob([content],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); URL.revokeObjectURL(a.href); }
function escapeHtml(value:unknown){ return String(value ?? '').replace(/[&<>]/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch] ?? ch)); }
export function ExportCenterScreen(){ const snapshot=useMasterProStore(s=>s.simulationSnapshots[s.selectedRouteId]); const route=useMasterProStore(s=>s.routes[s.selectedRouteId]); const comparisons=useMasterProStore(s=>s.comparisons); const warnings=useMasterProStore(s=>s.warnings);
 function exportExcelHtml(){ if(!snapshot) return; const simRows=snapshot.rows.map(r=>[r.month,Math.round(r.openingBalance),r.regularDeposit,r.oneTimeDeposit,Math.round(r.returnAmount),Math.round(r.managementFee),Math.round(r.eventWithdrawal),r.eventNumber??'',Math.round(r.taxPaid),Math.round(r.loanRepayment),Math.round(r.closingBalance),r.liquidityStatus,r.actionDetails?.map(d=>`${d.title}: ${d.explanation}`).join(' | ')??'']);
  const summary=[['מסלול',route.name],['הפקדות',snapshot.totals.deposits],['תשואות',Math.round(snapshot.totals.returns)],['דמי ניהול',Math.round(snapshot.totals.fees)],['משיכות',Math.round(snapshot.totals.withdrawals)],['מסים',Math.round(snapshot.totals.taxes)],['הלוואות',Math.round(snapshot.totals.loans)],['יתרה סופית',Math.round(snapshot.totals.endingBalance)]];
  const table=(title:string,headers:string[],rows:unknown[][])=>`<h2>${title}</h2><table border="1"><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${escapeHtml(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const html=`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><style>body{font-family:Arial}table{border-collapse:collapse;margin-bottom:24px}th{background:#172554;color:#fff}td,th{padding:6px 10px}</style></head><body>${table('סיכום', ['שדה','ערך'], summary)}${table('סימולציה', ['חודש','יתרת פתיחה','הפקדה','חד פעמי','תשואה','דמי ניהול','משיכה','אירוע','מס','החזר הלוואה','יתרת סגירה','סטטוס','פירוט'], simRows)}${table('אזהרות', ['חומרה','כותרת','הודעה','חודש'], warnings.map(w=>[w.severity,w.title,w.message,w.month??'']))}${comparisons.length?table('השוואות',['מסלול','יתרה','פערים','מינוף','אזהרות'],comparisons.map(c=>[c.name,Math.round(c.endingBalance),Math.round(c.deficits),Math.round(c.leverage),c.warnings])):''}</body></html>`;
  downloadBlob(html,`STRATPLAN-${route.id}-simulation.xls`,'application/vnd.ms-excel;charset=utf-8');
 }
 function exportCsv(){ if(!snapshot) return; const csv=['month,opening,deposit,return,fee,withdrawal,tax,closing',...snapshot.rows.map(r=>[r.month,r.openingBalance,r.regularDeposit,r.returnAmount,r.managementFee,r.eventWithdrawal,r.taxPaid,r.closingBalance].join(','))].join('\n'); downloadBlob(csv,'stratplan-simulation.csv','text/csv;charset=utf-8'); }
 return <><PageHeader title='Export Center' description='Excel/CSV מתוך Snapshots: סימולציה, סיכום, אזהרות והשוואות.' actions={<div className='action-rows'><Button onClick={exportExcelHtml} disabled={!snapshot}>יצוא Excel</Button><Button onClick={exportCsv} disabled={!snapshot}>יצוא CSV</Button></div>}/><div className='grid cards-3'><Card><h3>מקור נתונים</h3><p>היצוא מבוסס Snapshot ולא DOM/UI.</p></Card><Card><h3>סטטוס</h3><b>{snapshot?'מוכן ליצוא':'יש להריץ סימולציה תחילה'}</b></Card><Card><h3>יתרה</h3><b>{snapshot?formatMoney(snapshot.totals.endingBalance):'—'}</b></Card></div></> }
